config:
    logging:
        file_log_enabled: true
        file_log_path: logs/debug.log
    programs:
        QMPlay2:
            owner: 'zaps166'
            repo: 'QMPlay2'
            id: 'qmplay2'
            title: 'qmplay2 (Install)'
            authors: 'Błażej Szczygieł (zaps166)'
            projectUrl: 'https://github.com/zaps166/QMPlay2'
            iconUrl: 'https://raw.githubusercontent.com/zaps166/QMPlay2/master/src/gui/Windows/QMPlay2.ico'
            licenseUrl: 'https://raw.githubusercontent.com/zaps166/QMPlay2/master/LICENSE'
            tags: 'qmplay2 videoplayer mediaplayer youtube prostopleer freeware'
            summary: 'QMPlay2 is a video and audio player which can play most formats and codecs.'
            description: 'QMPlay2 is a video and audio player. It can play all formats supported by FFmpeg, libmodplug (including J2B and SFX). It also supports Audio CD, raw files, Rayman 2 music and chiptunes. It contains YouTube and Prostopleer browser.'
            #checksumType: 'sha-1'
            checksumType: 'sha256'
            silentArgs: '--Auto'
            regexp_mask:
                choco_ver: '\d{2}\.\d{2}\.\d{2}'
                #checksum_32: '(.{40})\s\sQMPlay2-Win(32)'
                #checksum_64: '(.{40})\s\sQMPlay2-Win(64)'
                changelog_prepare: '.*Changes.+\n(.*\n)*---'
                changelog_final: '^(?!.*Linux|.*AppImage|.*KDE|.*Changes).*,'
                
